### ISSUE TITLE
Can't request again a new private server

### ISSUE THREAD

**Issue by unixfox** [bolt-rip/nerve#16]
![image](https://user-images.githubusercontent.com/4016501/104938710-55deb000-59a7-11eb-9571-9aec6a1150c7.png)

For some unknown reason I can't request again a new private server on the bungeecord test server. The private server is not even deployed on the Kubernetes cluster.

1 possible way of fixing this error properly:

Dialog with Kubernetes API for checking if the private server exist (good way!). Example code here: https://github.com/bolt-rip/examples/blob/master/kubernetes/java/src/main/java/example/CheckExistPrivateServer.java

**Comment by dentmaged** [comment]
Closed by https://github.com/bolt-rip/nerve/commit/ee2590af43b074b4024e272b371c18c91e5920d2
